[package]
name = "enwiro"
version = "0.3.18"
edition = "2024"
description = "Simplify your workflow with dedicated project environments for each workspace in your window manager"
license = "GPL-3.0-or-later"
repository.workspace = true

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
anyhow = "1"
clap = { version = "4.5.4", features = ["derive"] }
confy = "2.0.0"
enwiro-logging.workspace = true
home.workspace = true
serde = { version = "1.0.197", features = ["derive"] }
serde_json = "1"
strum = { version = "0.27.0", features = ["derive"] }
strum_macros = "0.27.0"
notify-rust = "4"
tracing.workspace = true
dirs = "6"
libc = "0.2"
signal-hook = "0.3"

[dev-dependencies]
assertables = "9.0.0"
filetime = "0.2"
rstest = "0.26.0"
tempfile = "3.25.0"
