[package]
name = "enwiro"
version = "0.3.2"
edition = "2021"
description = "Simplify your workflow with dedicated project environments for each workspace in your window manager"
license = "GPL-3.0-or-later"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
clap = { version = "4.5.4", features = ["derive"] }
confy = "0.6.1"
home = "0.5.9"
path_lookup = "0.1.5"
serde = "1.0.197"
serde_derive = "1.0.197"
strum = { version = "0.26.2", features = ["derive"] }
strum_macros = "0.26.2"

[dev-dependencies]
assertables = "7.0.1"
rand = "0.8.5"
rstest = "0.18.2"
